version: "3"

services:
  nodeosd:
    image: rust-eos-dev:0.2.0
    # Append --delete-all-blocks to the below command if you want a brand new blockchain.
    command: nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::http_plugin --plugin eosio::history_plugin --plugin eosio::history_api_plugin --access-control-allow-origin='*' --contracts-console --http-validate-host=false --http-server-address=0.0.0.0:8888 --verbose-http-errors --filter-on '"*"' "|" "tee nodeos.log" --max-transaction-time=200 --delete-all-blocks
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - ../:/project
      - dir-contract-nodeos-data-volume:/opt/eosio/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keosd:
    image: rust-eos-dev:0.2.0
    command: keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=keosd:8900 --http-alias=localhost:8900
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - ../:/project
      - dir-contract-keosd-data-volume:/opt/eosio/bin/data-dir
    stop_grace_period: 10m
    env_file:
        - eos.env
  dir-contract:
    image: rust-eos-dev:0.2.0
    volumes:
      - ../:/project
      - dir-contract-cargo-data-volume:/usr/local/cargo
    tty: true

volumes:
 dir-contract-nodeos-data-volume:
   external: true
 dir-contract-keosd-data-volume:
   external: true
 dir-contract-cargo-data-volume:
   external: true
