[package]
name = "eosio_token"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
eosio = "0.3.0"
eosio_cdt = "0.3.0"
eosio_numstr = "0.3.0"
